
function T=TransMatrix(a,anpha,d,theta)
T=[cosd(theta),-sind(theta)*cosd(anpha),sind(theta)*sind(anpha) ,a*cosd(theta);...
   sind(theta),cosd(anpha)*cosd(theta) ,-cosd(theta)*sind(anpha),a*sind(theta);...
   0          ,sind(anpha)             ,cosd(anpha)             ,d           ;...
   0          ,0                       ,0                       ,1          ];
end 

